### DISCUSSION TITLE
Is it possible to add Candy GVF4137TWHN/2-07 ?

### DISCUSSION THREAD

**Discussion by TimerZero13** [ofalvai/home-assistant-candy#120] [Device support improvements]
When trying to add an Candy GVF4137TWHN/2-07 washing machine, an error is displayed: "Failed to detect encryption, check logs". What can I do to add my washing machine to Home Assistant?

**Comment by ofalvai** [comment]
Can you try raising the log level of this integration and paste what you see in the logs when you try to add the device?
You can edit the log level in configuration.yml like so:

```yml
logger:
  default: warning
  logs:
    custom_components.candy: debug
```
