### ISSUE TITLE
Washing machine status randomly updating to Idle while WM turned OFF

### ISSUE THREAD

**Issue by kino90** [ofalvai/home-assistant-candy#13]
Hi! First of all thanks for your work on this integration, much appreciated! 😉 
I'm having some weird behaviour with a binary sensor I made using the washing machine sensor..

``` yaml
template:
  - binary_sensor:
      - name: Washing Machine status
        state: >
          {{ states("sensor.washing_machine") | upper not in ["UNAVAILABLE"] }}
        icon: mdi:washing-machine
```

This should be pretty straightforward, however, it's randomly  reporting as "On" (see image)

![image](https://user-images.githubusercontent.com/1820036/135891438-44c6dd90-8385-4fcc-9896-b05c4d2af2e9.png)

I used Developer Tools to check the template, and saw that the state was Idle, even if the washing machine is turned Off 

![image](https://user-images.githubusercontent.com/1820036/135891595-55a6ce72-6120-44d3-a649-3fe9528fc8c8.png)

Is my Washing Machine possessed by some weird wifi evil? 😄

**Comment by ofalvai** [comment]
That's pretty strange, I've never seen my washing machine respond to requests while it's physically turned off.

Can you try raising the log level of this integration and paste what you see in the logs when the machine becomes available?
You can edit the log level in `configuration.yml` like so:

```yaml
logger:
  default: warning
  logs:
    custom_components.candy: debug
```
